services:
  - type: web
    name: portfolio
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT --workers 3 --timeout 120 DjangoProject.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-6n+$^sa+%qex3ye#35^1zjb11s$l(+^i9w7&-r84c28r_tk*7s
      - key: ALLOWED_HOSTS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: EMAIL_HOST_USER
        value: nguyenminh090903@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: vtgmfkpwmuthqinn
